services:
 adminer-service:
  image: adminer
  restart: unless-stopped
  container_name: adminer_new_one
  depends_on:
   - postgres-service
  networks:
   - projecto_prueba
  ports:
   - "8080:8080"
  environment:
   - ADMINER_DESIGN=pepa-linha-dark

 fastapi-service:
  build:
   context: .
   dockerfile: Dockerfile
  image: fastapi
  container_name: fastapi_new_one
  restart: unless-stopped
  depends_on:
   - postgres-service
  ports:
   - "8000:8000"
  environment:
   - POSTGRES_SERVER=postgres
   - POSTGRES_PORT=${POSTGRES_PORT}
   - POSTGRES_DB=${POSTGRES_DB}
   - POSTGRES_USER=${POSTGRES_USER}
   - POSTGRES_PASSWORD=Secret$$123
  networks:
   - projecto_prueba
  volumes:
   - ".:/app"
  # command: "./startup.sh"

 smtp-service:
  image: axllent/mailpit
  restart: unless-stopped
  container_name: smtp_new_one
  networks:
   - projecto_prueba
  ports:
   - "8025:8025"
   - "1025:1025"

 postgres-service:
  image: postgres:17
  container_name: postgres_new_one
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=Secret$$123
   - POSTGRES_DB=fastapi
  networks:
   - projecto_prueba
  volumes:
   - projecto_prueba:/var/lib/postgresql/data

networks:
 projecto_prueba:
volumes:
 projecto_prueba:
  external: true
