"""Relaciones

Revision ID: 5348ae975a24
Revises: 817f3ecb6ea4
Create Date: 2024-11-29 23:01:57.037121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5348ae975a24'
down_revision: Union[str, None] = '817f3ecb6ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('enlatado_uuid', sa.UUID(as_uuid=150), nullable=False))
    op.add_column('notifications', sa.Column('dulce_uuid', sa.UUID(as_uuid=150), nullable=False))
    op.add_column('notifications', sa.Column('bebida_uuid', sa.UUID(as_uuid=150), nullable=False))
    op.add_column('notifications', sa.Column('carne_uuid', sa.UUID(as_uuid=150), nullable=False))
    op.add_column('notifications', sa.Column('comida_uuid', sa.UUID(as_uuid=150), nullable=False))
    op.add_column('notifications', sa.Column('salsa_uuid', sa.UUID(as_uuid=150), nullable=False))
    op.create_foreign_key(None, 'notifications', 'enlatados', ['enlatado_uuid'], ['uuid'])
    op.create_foreign_key(None, 'notifications', 'bebidas', ['bebida_uuid'], ['uuid'])
    op.create_foreign_key(None, 'notifications', 'salsas', ['salsa_uuid'], ['uuid'])
    op.create_foreign_key(None, 'notifications', 'carnes', ['carne_uuid'], ['uuid'])
    op.create_foreign_key(None, 'notifications', 'dulces', ['dulce_uuid'], ['uuid'])
    op.create_foreign_key(None, 'notifications', 'comidas', ['comida_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'salsa_uuid')
    op.drop_column('notifications', 'comida_uuid')
    op.drop_column('notifications', 'carne_uuid')
    op.drop_column('notifications', 'bebida_uuid')
    op.drop_column('notifications', 'dulce_uuid')
    op.drop_column('notifications', 'enlatado_uuid')
    # ### end Alembic commands ###