"""Relaciones 2

Revision ID: 7cb4ab4211ee
Revises: 5348ae975a24
Create Date: 2024-11-29 23:04:46.666480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb4ab4211ee'
down_revision: Union[str, None] = '5348ae975a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('user_uuid', sa.UUID(as_uuid=150), nullable=False))
    op.create_foreign_key(None, 'notifications', 'users', ['user_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'user_uuid')
    # ### end Alembic commands ###