"""Creación de tablas

Revision ID: 817f3ecb6ea4
Revises: 
Create Date: 2024-11-29 22:10:04.590715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '817f3ecb6ea4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bebidas',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('coste', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('time_get', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_bebidas_uuid'), 'bebidas', ['uuid'], unique=False)
    op.create_table('carnes',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('coste', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('time_get', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_carnes_uuid'), 'carnes', ['uuid'], unique=False)
    op.create_table('comidas',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('coste', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('time_get', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_comidas_uuid'), 'comidas', ['uuid'], unique=False)
    op.create_table('dulces',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('coste', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('time_get', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_dulces_uuid'), 'dulces', ['uuid'], unique=False)
    op.create_table('enlatados',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('coste', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('time_get', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_enlatados_uuid'), 'enlatados', ['uuid'], unique=False)
    op.create_table('notifications',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_notifications_uuid'), 'notifications', ['uuid'], unique=False)
    op.create_table('salsas',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('coste', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('time_get', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_salsas_uuid'), 'salsas', ['uuid'], unique=False)
    op.create_table('users',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_salsas_uuid'), table_name='salsas')
    op.drop_table('salsas')
    op.drop_index(op.f('ix_notifications_uuid'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_enlatados_uuid'), table_name='enlatados')
    op.drop_table('enlatados')
    op.drop_index(op.f('ix_dulces_uuid'), table_name='dulces')
    op.drop_table('dulces')
    op.drop_index(op.f('ix_comidas_uuid'), table_name='comidas')
    op.drop_table('comidas')
    op.drop_index(op.f('ix_carnes_uuid'), table_name='carnes')
    op.drop_table('carnes')
    op.drop_index(op.f('ix_bebidas_uuid'), table_name='bebidas')
    op.drop_table('bebidas')
    # ### end Alembic commands ###